time_precision: MSECS
logging_level: ERROR
reactors:
  frost_link:
    logging_level: ERROR
    parameters:
      data_model_path: "resources/data_model/frost_link.yml"
    reactors:
      message_filter:
        logging_level: ERROR
  conveyor:
    logging_level: ERROR
    parameters:
      data_model_path: "resources/data_model/mqtt/conveyor.yml"
      conveyor_graph: "resources/conveyor_graph/conveyor_graph.gml"
      pallet_metric: "DISTANCE"
    reactors:
     message_filter:
       logging_level: ERROR
     conveyor_belt:
       logging_level: ERROR
       reactors:
          controller:
            logging_level: ERROR
          Segment_1:
            logging_level: ERROR
            parameters:
              segment_time: 16300
          Segment_2:
              logging_level: ERROR
              parameters:
                segment_time: 20200            
          Segment_3:
            logging_level: ERROR
            parameters:
              segment_time: 13250
          Segment_4:
            logging_level: ERROR
            parameters:
              segment_time: 8691
          Segment_5:
            logging_level: ERROR
            parameters:
              segment_time: 6900
          Segment_6:
            logging_level: ERROR
            parameters:
              segment_time: 17500
          Segment_7:
            logging_level: ERROR
            parameters:
              segment_time: 20200
          Segment_8:
            logging_level: ERROR
            parameters:
              segment_time: 12700
          EM:
            logging_level: ERROR
            parameters:
              mutex_time: 2500
          HB: 
            logging_level: ERROR
            parameters:
              interchange_time: 4800           
          Bay2:
            logging_level: ERROR
            reactors:      
              "1":
                logging_level: ERROR
                parameters:
                  forward_time: 2077
                  backward_time: 1272
              "2":
                logging_level: ERROR
                parameters:
                  forward_time: 4857
                  backward_time: 1766
              "3":
                logging_level: ERROR
                parameters:
                  forward_time: 2000
                  backward_time: 4413
          Bay3:
            logging_level: ERROR
            reactors:      
              "1":
                logging_level: ERROR
                parameters:
                  forward_time: 3779
                  backward_time: 2833
              "2":
                logging_level: ERROR
                parameters:
                  forward_time: 2173
                  backward_time: 3925
              "3":
                logging_level: ERROR
                parameters:
                  forward_time: 2000
                  backward_time: 2061
          Bay4:
            logging_level: ERROR
            reactors:    
              "1":
                logging_level: ERROR
                parameters:
                  forward_time: 2603
                  backward_time: 1585
              "2":
                logging_level: ERROR
                parameters:
                  forward_time: 4292
                  backward_time: 2809
              "3":
                logging_level: ERROR
                parameters:
                  forward_time: 2000
                  backward_time: 3492
          LoadUnloadZone:
            logging_level: ERROR
          # Additional conveyor components
          H:
            logging_level: ERROR
          IC:
            logging_level: ERROR  
          A:
            logging_level: ERROR
          B:
            logging_level: ERROR
          C:
            logging_level: ERROR
          D:
            logging_level: ERROR
          E:
            logging_level: ERROR
          F:
            logging_level: ERROR
          FA:
            logging_level: ERROR
          I:
            logging_level: ERROR
          L:
            logging_level: ERROR
          M:
            logging_level: ERROR
          LD:
            logging_level: ERROR
          Bay1_1:
            logging_level: ERROR
  scheduler:
    logging_level: DEBUG
    parameters:
      # DEMO GADGET
      data_model_path: "resources/scheduler_tasks/demo-gadget-scheduler.yml"
      scheduling_instance: "resources/schedules/simulation-gadget-demo.json"
      # DEMO LEGO
      # data_model_path: "resources/scheduler_tasks/demo-lego-scheduler.yml"
      # scheduling_instance: "resources/schedules/simulation-lego-demo.json"
      task_mapping: 
        LD: /Scheduler/LD
        RBTC: /Scheduler/RBTC
        QC: /Scheduler/QC
        DISASSEMBLE: /Scheduler/DISASSEMBLE
        RESERVE: /Scheduler/RESERVE
        PUT_BACK: /Scheduler/PUT_BACK
        RESERVE_PALLET: /Scheduler/RESERVE_PALLET
        GOTO_WAREHOUSE: /Scheduler/GOTO_WAREHOUSE
        EXTRACT_TRAY: /Scheduler/EXTRACT_TRAY
        PICK_PARTS: /Scheduler/PICK_PARTS
        KAIROS_TO_BAY: /Scheduler/KAIROS_TO_BAY
        BOARD_PALLET_TO_BAY: /Scheduler/BOARD_PALLET_TO_BAY
        LOAD_BOARD: /Scheduler/LOAD_BOARD
        LOAD_COVERS: /Scheduler/LOAD_COVERS
        RESET_MOBILE: /Scheduler/RESET_MOBILE
        QC_BOARD: /Scheduler/QC_BOARD
        BUFFER_BOARD: /Scheduler/BUFFER_BOARD
        QC_COVERS: /Scheduler/QC_COVERS
        BIN_COVERS: /Scheduler/BIN_COVERS
        RESERVE_AFTER_FAIL: /Scheduler/RESERVE_AFTER_FAIL
        GOTO_WAREHOUSE_2: /Scheduler/GOTO_WAREHOUSE_2
        PICK_COVERS_2: /Scheduler/PICK_COVERS_2
        KAIROS_TO_BAY_2: /Scheduler/KAIROS_TO_BAY_2
        COVER_PALLET_TO_BAY_2: /Scheduler/COVER_PALLET_TO_BAY_2
        LOAD_COVERS_2: /Scheduler/LOAD_COVERS_2
        RESET_MOBILE_2: /Scheduler/RESET_MOBILE_2
        QC_COVERS_2: /Scheduler/QC_COVERS_2
        ASSEMBLE_GADGET: /Scheduler/ASSEMBLE_GADGET
        ENGRAVE_GADGET: /Scheduler/ENGRAVE_GADGET
        MILLING_POST: /Scheduler/MILLING_POST
        GADGET_TO_BAY: /Scheduler/GADGET_TO_BAY

    reactors:
      message_filter:
        logging_level: ERROR
  cell1:
    logging_level: ERROR
    parameters:
      data_model_path: "resources/data_model/mqtt/cell1.yml"
    reactors:
      message_filter:
        logging_level: ERROR
  cell2:
    logging_level: ERROR
    parameters:
      data_model_path: "resources/data_model/mqtt/cell2.yml"
    reactors:
      message_filter:
        logging_level: ERROR
  cell4:
    logging_level: ERROR
    parameters:
      data_model_path: "resources/data_model/mqtt/cell4.yml"
    reactors:
      message_filter:
        logging_level: ERROR
  cell5:
    logging_level: ERROR
    parameters:
      data_model_path: "resources/data_model/mqtt/cell5.yml"
      path: "src/fmu/QualityCell.fmu"
      time_step: 100
    reactors:
      message_filter:
        logging_level: ERROR
  rbkairos_a:
    logging_level: ERROR
    parameters:
      data_model_path: "resources/data_model/mqtt/rbkairos_a.yml"
    reactors:
      message_filter:
        logging_level: ERROR
  rbkairos_b:
    logging_level: ERROR
    parameters:
      data_model_path: "resources/data_model/mqtt/rbkairos_b.yml"
    reactors:
      message_filter:
        logging_level: ERROR
  warehouse:
    logging_level: ERROR
    parameters:
      data_model_path: "resources/data_model/mqtt/warehouse.yml"
    reactors:
      message_filter:
        logging_level: ERROR
  etensil:
    logging_level: ERROR
    parameters:
      data_model_path: "resources/data_model/mqtt/etensil.yml"
    reactors:
      message_filter:
        logging_level: ERROR
  recipe_timer:
    logging_level: ERROR
    parameters:
      data_model_path: "resources/data_model/recipe_timer.yml"
    reactors:
      message_filter:
        logging_level: ERROR

