time_precision: MSECS
logging_level: WARNING
reactors:
  frost_link:
    logging_level: INFO
    parameters:
      data_model_path: "resources/data_model/frost_link.yml"
  conveyor:
    logging_level: DEBUG
    parameters:
      data_model_path: "resources/data_model/opcua-conveyor.yml"
  scheduler:
    logging_level: DEBUG
    parameters:
      data_model_path: "resources/data_model/opcua-conveyor-scheduler.yml"
      scheduling_instance: "resources/schedules/opcua-conveyor-schedule.json"
      task_mapping: 
        StartTask1: /Scheduler/StartTask1
        StartTask2: /Scheduler/StartTask2
