conveyor_obj = "Objects/ConveyorHMI/ConveyorObjects/"
Pallets = "Pallets/"
Bayes = "Bayes/"
Segments = "Segments/"
Commands = "Commands/"
commands_pointer = "Objects/ConveyorHMI/ConveyorDataExchange/Commands/ConveyorCommandsPointer/"
IndexPosition = "IndexPosition"
setDestination = "setDestination"
PalletPosition = "PalletPosition{n}"
palletNum = "palletNum"
Pallet = "Pallet{n}"
Pallet1 = Pallet.format(n=1)
Pallet2 = Pallet.format(n=2)
Pallet3 = Pallet.format(n=3)
Pallet4 = Pallet.format(n=4)
Pallet5 = Pallet.format(n=5)
Pallet6 = Pallet.format(n=6)
Pallet7 = Pallet.format(n=7)
Pallet8 = Pallet.format(n=8)
Pallet9 = Pallet.format(n=9)
Pallet10 = Pallet.format(n=10)
Bay = "Bay{n}"
Bay1 = Bay.format(n=1)
Bay2 = Bay.format(n=2)
Bay3 = Bay.format(n=3)
Bay4 = Bay.format(n=4)
Bay5 = "LoadUnloadZone"
Segment = "Segment{n}"
Segment1 = Segment.format(n=1)
Segment2 = Segment.format(n=2)
Segment3 = Segment.format(n=3)
Segment4 = Segment.format(n=4)
Segment5 = Segment.format(n=5)
Segment6 = Segment.format(n=6)
Segment7 = Segment.format(n=7)
Segment8 = Segment.format(n=8)
FIFO = "FIFO"
size = "size"
item = "item{n}"